In [1]:
import pulp
import numpy as np
import time

In [2]:
start = time.time()

In [3]:
# Create Random demand and Pobability for SGD

import random
l1=[60,80,100,120,140]
l2=[100,150,200,250,300]
l3=[90,120,150,180,210]
l4=[70,120,170,220,270]

w=[0.02275 , 0.13591, 0.68268, 0.13591, 0.02275]
# print(random.choices(l1, weights=w))
def rnddm(l, w):
    dm = random.choices(l, weights=w)
    p = w[l.index(dm[0])]
    return dm[0], p

In [4]:
demands = ['l1','l2','l3','l4']
h=1   # holding cost
p=4   # penalty cost for shortage 
c0i=0.5 #basic direct transshipment cost
cs=100000000000000000 #basic direct transshipment cost

In [5]:
#define trans from i to j
count=0
trans=[]
for i in demands:
    for j in demands:
        trans.append((i,j))
    
    #del trans[count][count]
    count=count+1
del trans[::5]

In [6]:
#define trans from j to i
count=0
trans_r=[]
for i in demands:
    for j in demands:
        trans_r.append((j,i))
    
    #del trans[count][count]
    count=count+1
del trans_r[::5]

In [7]:
#first-stage variable: order-up-to quantity
s = pulp.LpVariable.dicts("s",(demands) ,lowBound=0, cat='Continuous')
#ending inventory held at retailer i. 
e=pulp.LpVariable.dicts("e",(demands) ,lowBound=0, cat='Continuous')
#stock at retailer i used to satisfy demand at retailer i
f=pulp.LpVariable.dicts("f",(demands) ,lowBound=0, cat='Continuous') 
#inventory at retailer i increased through replenishment
q=pulp.LpVariable.dicts("q",(demands) ,lowBound=0, cat='Continuous')
#amount of shortage at the retailer i. (Assume all past shortage are omitted)
r=pulp.LpVariable.dicts("r",(demands) ,lowBound=0, cat='Continuous')
#stock at retailer i used to meet demand at retailer j, using the transshipment option.
t=pulp.LpVariable.dicts("t",(trans) ,lowBound=0, cat='Continuous')

# S coefficient
Cs=[[1,0,0,0],
   [0,0,0,0],
   [1,0,0,0],
   [0,1,0,0],
   [0,0,0,0],
   [0,1,0,0],
   [0,0,1,0],
   [0,0,0,0],
   [0,0,1,0],
   [0,0,0,1],
   [0,0,0,0],
   [0,0,0,1],
   [0,0,0,0]]


Cs = [[-1,0,0,0],[0,0,0,0],[-1,0,0,0],[0,-1,0,0],[0,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,0],
    [0,0,-1,0],[0,0,0,-1],[0,0,0,0],[0,0,0,-1],[0,0,0,0]]


In [8]:
def SGD(sample_size, iteration_time, alpha): 
    Ds = []
    Ps = []
    
    for i in range(sample_size):
        l1_sample = rnddm(l1,w)
        l2_sample = rnddm(l2,w)
        l3_sample = rnddm(l3,w)
        l4_sample = rnddm(l4,w)

        demand = {'l1':l1_sample[0],'l2':l2_sample[0],'l3':l3_sample[0],'l4':l4_sample[0]}
        probability = l1_sample[1]*l2_sample[1]*l3_sample[1]*l4_sample[1]

        Ds.append(demand)
        Ps.append(probability)
    
    scenarios = list(range(0,len(Ds)))
    subgradient = [0,0,0,0] #initial subgradient = -c, in this case, is 0
    Cs = [[-1,0,0,0],
           [0,0,0,0],
           [-1,0,0,0],
           [0,-1,0,0],
           [0,0,0,0],
           [0,-1,0,0],
           [0,0,-1,0],
           [0,0,0,0],
           [0,0,-1,0],
           [0,0,0,-1],
           [0,0,0,0],
           [0,0,0,-1],
           [0,0,0,0]]




    s = {'l1': 50, 'l2': 200, 'l3': 50, 'l4': 180} # initialize s
    
    
    for i in range(iteration_time):
        step=i
        up=0
        sub=[]
        for j in scenarios:
            transship = pulp.LpProblem("transship",pulp.LpMinimize)
            # Objective
            transship += pulp.lpSum([h * e[i] for i in demands]
                                    + [cs * t[(i,j)] for (i,j) in trans[3:]]
                                    + [c0i * t[(i,j)] for (i,j) in trans[:3]]
                                    + [p * r[i] for i in demands])

            opt=[]
            obj=[]
            d=Ds[j]
            start=0
            up=0
            for i in demands:  

                transship += e[i] + \
                                f[i] + \
                                pulp.lpSum(t[j] for j in trans[start:start+3])==s[i]

                transship += r[i] + \
                                f[i] + \
                                pulp.lpSum(t[j] for j in trans_r[start:start+3])==d[i]

                transship += e[i]+q[i]==s[i]
                start=start+3

            transship += pulp.lpSum(r[i]+q[i] for i in demands)==pulp.lpSum(d[i] for i in demands)

            #solve    
            transship.solve()
            
            
            
            dual = []
            for name, c in list(transship.constraints.items()):
                dual.append(c.pi)

          
            subgradient = subgradient - Ps[j]*(np.array(dual).T.dot(Cs))
            
#             up=up+Ps[j]*transship.objective.value()
            
            sub.append(Ps[j]*transship.objective.value())
            
        subgradient=subgradient/np.array(Ps).sum()
        
        up=np.array(sub).sum()/np.array(Ps).sum()
        
        if (abs(subgradient[0]-0)<0.01)&(abs(subgradient[1]-0)<0.01)&(abs(subgradient[2]-0)<0.01)&(abs(subgradient[3]-0)<0.01):
            break
        
        else:
            s_new = list(s.values()) - (alpha)*np.array(subgradient) 

            for n in range(4):
                if s_new[n]<0:
                    s_new[n] = 0

            s = {'l1':s_new[0],'l2':s_new[1],'l3':s_new[2],'l4':s_new[3]} # update s to next iteration
        print(subgradient,s)

In [9]:
SGD(sample_size=50,iteration_time=3000,alpha=0.1)

[-4.         -0.46359699 -4.          0.60963183] {'l1': 50.4, 'l2': 200.0463596990328, 'l3': 50.4, 'l4': 179.93903681684827}
[-5.22909424  0.6084302  -5.22909424  0.79695558] {'l1': 50.922909424346685, 'l2': 199.98551667867085, 'l3': 50.922909424346685, 'l4': 179.85934125932775}
[-5.60676241 -3.63828284 -5.60676241  0.85451521] {'l1': 51.48358566517645, 'l2': 200.34934496259527, 'l3': 51.48358566517645, 'l4': 179.77388973843142}
[-5.72280985 -0.36706682 -5.72280985  0.87220176] {'l1': 52.05586665018957, 'l2': 200.3860516447763, 'l3': 52.05586665018957, 'l4': 179.6866695621724}
[-5.75846816  0.63809137 -5.75846816  0.87763637] {'l1': 52.63171346627086, 'l2': 200.3222425075532, 'l3': 52.63171346627086, 'l4': 179.59890592488213}
[-5.76942502  0.94694991 -5.76942502  0.87930628] {'l1': 53.20865596796192, 'l2': 200.22754751657837, 'l3': 53.20865596796192, 'l4': 179.5109752963856}
[-5.77279177  1.04185397 -5.77279177  0.8798194 ] {'l1': 53.78593514487187, 'l2': 200.12336211934084, 'l3': 53.

[-5.75805057  0.95107714 -5.77428516  0.88004701] {'l1': 81.49957236171626, 'l2': 200.20113502038942, 'l3': 81.5024376880027, 'l4': 175.19877780375057}
[-5.75687803  1.04312216 -5.77428516  0.88004701] {'l1': 82.0752601651546, 'l2': 200.09682280440194, 'l3': 82.07986620437413, 'l4': 175.1107731027491}
[-5.75651775  1.07140516 -5.77428516  0.88004701] {'l1': 82.65091193972849, 'l2': 199.9896822881891, 'l3': 82.65729472074555, 'l4': 175.02276840174764}
[-5.75640704 -3.49602288 -5.77428516  0.88004701] {'l1': 83.2265526435849, 'l2': 200.3392845757042, 'l3': 83.23472323711698, 'l4': 174.93476370074617}
[-5.75637302 -0.3233541  -5.77428516  0.88004701] {'l1': 83.80218994570252, 'l2': 200.37161998531167, 'l3': 83.81215175348841, 'l4': 174.8467589997447}
[-5.75636257  0.65152314 -5.77428516  0.88004701] {'l1': 84.37782620255577, 'l2': 200.30646767159936, 'l3': 84.38958026985983, 'l4': 174.75875429874324}
[-5.75635936  0.95107714 -5.77428516  0.88004701] {'l1': 84.9534621382269, 'l2': 200.2113

[-4.93225637  0.6592391  -5.64055378  0.88004701] {'l1': 111.06991098949185, 'l2': 200.25893036917225, 'l3': 112.559766743904, 'l4': 170.4465239496714}
[-4.93017636  0.95344805 -5.63847377  0.88004701] {'l1': 111.56292862540901, 'l2': 200.16358556435756, 'l3': 113.1236141207616, 'l4': 170.35851924866992}
[-4.92953723  1.04385068 -5.63783464  0.88004701] {'l1': 112.05588234810752, 'l2': 200.05920049650754, 'l3': 113.68739758440078, 'l4': 170.27051454766845}
[-4.92934084  1.07162902 -5.63763825  0.88004701] {'l1': 112.54881643196373, 'l2': 199.9520375948435, 'l3': 114.25116140919776, 'l4': 170.182509846667}
[-4.92928049 -3.41425038 -5.6375779   0.88004701] {'l1': 113.04174448132294, 'l2': 200.29346263283747, 'l3': 114.81491919949777, 'l4': 170.09450514566552}
[-4.92926195 -0.29822757 -5.63755936  0.88004701] {'l1': 113.53467067644077, 'l2': 200.32328538986647, 'l3': 115.37867513555639, 'l4': 170.00650044466406}
[-4.92925625  0.65924385 -5.63755366  0.88004701] {'l1': 114.02759630179925, 

[ 0.23136052 -0.34214029 -0.42642707 -0.347011  ] {'l1': 123.26224194890402, 'l2': 199.9835078889033, 'l3': 128.37116342680812, 'l4': 170.0254932049737}
[ 0.23136052 -0.41348882 -0.42642707  0.50300452] {'l1': 123.23910589731187, 'l2': 200.02485677069555, 'l3': 128.41380613343168, 'l4': 169.97519275251122}
[ 0.23136052  0.62382712 -0.42642707 -0.14721556] {'l1': 123.21596984571973, 'l2': 199.96247405867726, 'l3': 128.45644884005523, 'l4': 169.98991430876814}
[ 0.23136052 -0.11667257 -0.42642707 -0.347011  ] {'l1': 123.19283379412758, 'l2': 199.97414131593288, 'l3': 128.49909154667878, 'l4': 170.02461540917898}
[ 0.23136052 -0.34420855 -0.42642707  0.50300452] {'l1': 123.16969774253543, 'l2': 200.00856217092937, 'l3': 128.54173425330234, 'l4': 169.97431495671648}
[ 0.23136052  0.64511511 -0.42642707 -0.14721556] {'l1': 123.14656169094329, 'l2': 199.94405065944775, 'l3': 128.5843769599259, 'l4': 169.9890365129734}
[ 0.23136052 -0.11013133 -0.42642707 -0.347011  ] {'l1': 123.1234256393511

[ 0.23136052 -0.10994156 -0.42642707 -0.347011  ] {'l1': 122.0128951629281, 'l2': 199.95100696719535, 'l3': 130.67386958448, 'l4': 170.00969288066847}
[ 0.23136052 -0.34214029 -0.42642707  0.50300452] {'l1': 121.98975911133596, 'l2': 199.9852209960516, 'l3': 130.71651229110356, 'l4': 169.95939242820597}
[ 0.23136052 -0.41348882 -0.42642707 -0.14721556] {'l1': 121.96662305974381, 'l2': 200.02656987784385, 'l3': 130.7591549977271, 'l4': 169.9741139844629}
[ 0.23136052  0.62382712 -0.42642707 -0.347011  ] {'l1': 121.94348700815166, 'l2': 199.96418716582556, 'l3': 130.80179770435066, 'l4': 170.00881508487373}
[ 0.23136052 -0.11667257 -0.42642707  0.50300452] {'l1': 121.92035095655952, 'l2': 199.9758544230812, 'l3': 130.84444041097422, 'l4': 169.95851463241124}
[ 0.23136052 -0.34420855 -0.42642707 -0.14721556] {'l1': 121.89721490496737, 'l2': 200.01027527807767, 'l3': 130.88708311759777, 'l4': 169.97323618866815}
[ 0.23136052  0.64511511 -0.42642707 -0.347011  ] {'l1': 121.87407885337522, '

[ 0.23136052  0.64511511 -0.42642707 -0.34137799] {'l1': 120.76354837695219, 'l2': 199.9416985231359, 'l3': 132.97657574215188, 'l4': 169.99414242066024}
[ 0.23136052 -0.11013133 -0.42642707 -0.40667198] {'l1': 120.74041232536004, 'l2': 199.95271165660006, 'l3': 133.01921844877543, 'l4': 170.03480961914312}
[ 0.23136052 -0.3421986  -0.42642707  0.48467228] {'l1': 120.7172762737679, 'l2': 199.9869315166499, 'l3': 133.061861155399, 'l4': 169.98634239087968}
[ 0.23136052 -0.41350674 -0.42642707 -0.15284858] {'l1': 120.69414022217575, 'l2': 200.02828219021376, 'l3': 133.10450386202254, 'l4': 170.00162724846413}
[ 0.23136052  0.62382161 -0.42642707  0.56266551] {'l1': 120.6710041705836, 'l2': 199.9659000287595, 'l3': 133.1471465686461, 'l4': 169.94536069792971}
[ 0.23136052 -0.11667426 -0.42642707 -0.12888332] {'l1': 120.64786811899145, 'l2': 199.9775674551889, 'l3': 133.18978927526965, 'l4': 169.9582490299876}
[ 0.23136052 -0.34420907 -0.42642707 -0.34137799] {'l1': 120.62473206739931, 'l2

[ 0.21947762 -0.34420855 -0.42642707 -0.14721556] {'l1': 119.53744029665185, 'l2': 200.00792314176581, 'l3': 135.27928189982376, 'l4': 169.98695458425075}
[ 0.21947762  0.64511511 -0.42642707 -0.347011  ] {'l1': 119.51549253490653, 'l2': 199.9434116302842, 'l3': 135.3219246064473, 'l4': 170.0216556846616}
[ 0.21947762 -0.11013133 -0.42642707  0.50300452] {'l1': 119.49354477316122, 'l2': 199.95442476374836, 'l3': 135.36456731307086, 'l4': 169.9713552321991}
[ 0.21947762 -0.3421986  -0.42642707 -0.14721556] {'l1': 119.47159701141591, 'l2': 199.9886446237982, 'l3': 135.40721001969442, 'l4': 169.98607678845602}
[ 0.21947762 -0.41350674 -0.42642707 -0.347011  ] {'l1': 119.44964924967061, 'l2': 200.02999529736206, 'l3': 135.44985272631797, 'l4': 170.02077788886686}
[ 0.21947762  0.62382161 -0.42642707  0.50300452] {'l1': 119.42770148792532, 'l2': 199.9676131359078, 'l3': 135.49249543294152, 'l4': 169.97047743640437}
[ 0.21947762 -0.11667426 -0.42642707 -0.14721556] {'l1': 119.40575372618002,

[ 0.21947762 -0.11667257 -0.42642707 -0.14721556] {'l1': 118.35226116240585, 'l2': 199.97521539391764, 'l3': 137.58198805749564, 'l4': 169.9711542599455}
[ 0.21947762 -0.34420855 -0.42642707 -0.347011  ] {'l1': 118.33031340066056, 'l2': 200.00963624891412, 'l3': 137.6246307641192, 'l4': 170.00585536035635}
[ 0.21947762  0.64511511 -0.42642707  0.50300452] {'l1': 118.30836563891526, 'l2': 199.9451247374325, 'l3': 137.66727347074274, 'l4': 169.95555490789386}
[ 0.21947762 -0.11013133 -0.42642707 -0.14721556] {'l1': 118.28641787716997, 'l2': 199.95613787089667, 'l3': 137.7099161773663, 'l4': 169.97027646415077}
[ 0.21947762 -0.3421986  -0.42642707 -0.347011  ] {'l1': 118.26447011542467, 'l2': 199.9903577309465, 'l3': 137.75255888398985, 'l4': 170.0049775645616}
[ 0.21947762 -0.41350674 -0.42642707  0.50300452] {'l1': 118.24252235367938, 'l2': 200.03170840451037, 'l3': 137.7952015906134, 'l4': 169.95467711209912}
[ 0.21947762  0.62382161 -0.42642707 -0.14721556] {'l1': 118.22057459193408, 

[ 0.21947762  0.62382712 -0.42642707  0.48467228] {'l1': 117.16708202815991, 'l2': 199.96526124381032, 'l3': 139.8846942151675, 'l4': 169.98338266636233}
[ 0.21947762 -0.11667257 -0.42642707 -0.15284858] {'l1': 117.14513426641462, 'l2': 199.97692850106594, 'l3': 139.92733692179107, 'l4': 169.99866752394675}
[ 0.21947762 -0.34420855 -0.42642707 -0.34874188] {'l1': 117.12318650466932, 'l2': 200.01134935606242, 'l3': 139.96997962841462, 'l4': 170.03354171196236}
[ 0.21947762  0.64511511 -0.42642707  0.50247267] {'l1': 117.10123874292402, 'l2': 199.9468378445808, 'l3': 140.01262233503817, 'l4': 169.9832944447445}
[ 0.21947762 -0.11013133 -0.42642707 -0.14737899] {'l1': 117.07929098117873, 'l2': 199.95785097804497, 'l3': 140.05526504166173, 'l4': 169.99803234342093}
[ 0.21947762 -0.3421986  -0.42642707 -0.34706122] {'l1': 117.05734321943343, 'l2': 199.9920708380948, 'l3': 140.09790774828528, 'l4': 170.0327384654252}
[ 0.21947762 -0.41350674 -0.42642707  0.50298909] {'l1': 117.03539545768814

[ 0.21947762 -0.41350674 -0.42642707  0.50300452] {'l1': 115.98190289391397, 'l2': 200.0293562681985, 'l3': 142.1874003728394, 'l4': 169.96839550768172}
[ 0.21947762  0.62382161 -0.42642707 -0.14721556] {'l1': 115.95995513216867, 'l2': 199.96697410674426, 'l3': 142.23004307946294, 'l4': 169.98311706393864}
[ 0.21947762 -0.11667426 -0.42642707 -0.347011  ] {'l1': 115.93800737042338, 'l2': 199.97864153317366, 'l3': 142.2726857860865, 'l4': 170.01781816434948}
[ 0.21947762 -0.34420907 -0.42642707  0.50300452] {'l1': 115.91605960867808, 'l2': 200.01306244015277, 'l3': 142.31532849271005, 'l4': 169.96751771188698}
[ 0.21947762  0.64511496 -0.42642707 -0.14721556] {'l1': 115.89411184693279, 'l2': 199.94855094464404, 'l3': 142.3579711993336, 'l4': 169.9822392681439}
[ 0.21947762 -0.11013138 -0.42642707 -0.347011  ] {'l1': 115.87216408518749, 'l2': 199.95956408301623, 'l3': 142.40061390595716, 'l4': 170.01694036855474}
[ 0.21947762 -0.34219862 -0.42642707  0.50300452] {'l1': 115.8502163234422,

[ 0.21947762 -0.3421986  -0.42642707  0.50300452] {'l1': 114.79672375966803, 'l2': 199.98971870178295, 'l3': 144.49010653051127, 'l4': 169.95259518337647}
[ 0.21947762 -0.41350674 -0.42642707 -0.14721556] {'l1': 114.77477599792273, 'l2': 200.03106937534682, 'l3': 144.53274923713482, 'l4': 169.9673167396334}
[ 0.21947762  0.62382161 -0.42642707 -0.347011  ] {'l1': 114.75282823617744, 'l2': 199.96868721389257, 'l3': 144.57539194375838, 'l4': 170.00201784004423}
[ 0.21947762 -0.11667426 -0.42642707  0.50300452] {'l1': 114.73088047443214, 'l2': 199.98035464032196, 'l3': 144.61803465038193, 'l4': 169.95171738758174}
[ 0.21947762 -0.34420907 -0.42642707 -0.14721556] {'l1': 114.70893271268685, 'l2': 200.01477554730107, 'l3': 144.66067735700548, 'l4': 169.96643894383865}
[ 0.21947762  0.64511496 -0.42642707 -0.347011  ] {'l1': 114.68698495094155, 'l2': 199.95026405179235, 'l3': 144.70332006362904, 'l4': 170.0011400442495}
[ 0.21947762 -0.11013138 -0.42642707  0.50300452] {'l1': 114.66503718919

[ 0.21947762 -0.11013133 -0.42642707 -0.34701105] {'l1': 113.61154462542208, 'l2': 199.95721194888142, 'l3': 146.79281268818315, 'l4': 170.03065876226248}
[ 0.21947762 -0.3421986  -0.42642707  0.50300451] {'l1': 113.58959686367679, 'l2': 199.99143180893125, 'l3': 146.8354553948067, 'l4': 169.9803583110987}
[ 0.21947762 -0.41350674 -0.42642707 -0.14721557] {'l1': 113.5676491019315, 'l2': 200.03278248249512, 'l3': 146.87809810143025, 'l4': 169.9950798677547}
[ 0.21947762  0.62382161 -0.42642707 -0.34701101] {'l1': 113.5457013401862, 'l2': 199.97040032104087, 'l3': 146.9207408080538, 'l4': 170.02978096828818}
[ 0.21947762 -0.11667426 -0.42642707  0.50300452] {'l1': 113.5237535784409, 'l2': 199.98206774747027, 'l3': 146.96338351467736, 'l4': 169.97948051586337}
[ 0.21947762 -0.34420907 -0.42642707 -0.14721556] {'l1': 113.50180581669561, 'l2': 200.01648865444938, 'l3': 147.0060262213009, 'l4': 169.99420207213188}
[ 0.21947762  0.64511496 -0.42642707 -0.347011  ] {'l1': 113.47985805495031, '

[ 0.21947762  0.64511496 -0.42642707 -0.347011  ] {'l1': 112.42636549117614, 'l2': 199.9479119154805, 'l3': 149.09551884585503, 'l4': 170.0148584398321}
[ 0.21947762 -0.11013138 -0.42642707  0.50300452] {'l1': 112.40441772943085, 'l2': 199.95892505385268, 'l3': 149.13816155247858, 'l4': 169.9645579873696}
[ 0.21947762 -0.34219862 -0.42642707 -0.14721556] {'l1': 112.38246996768555, 'l2': 199.99314491541062, 'l3': 149.18080425910213, 'l4': 169.97927954362652}
[ 0.21947762 -0.41350674 -0.42642707 -0.347011  ] {'l1': 112.36052220594026, 'l2': 200.0344955894379, 'l3': 149.22344696572569, 'l4': 170.01398064403736}
[ 0.21947762  0.62382161 -0.42642707  0.50300452] {'l1': 112.33857444419496, 'l2': 199.97211342812605, 'l3': 149.26608967234924, 'l4': 169.96368019157487}
[ 0.21947762 -0.11667426 -0.42642707 -0.14721556] {'l1': 112.31662668244967, 'l2': 199.9837808545992, 'l3': 149.3087323789728, 'l4': 169.97840174783178}
[ 0.21947762 -0.34420907 -0.42642707 -0.347011  ] {'l1': 112.29467892070437,

[ 0.21947762 -0.34420907 -0.3950136  -0.153012  ] {'l1': 111.2411863569302, 'l2': 200.01413651813752, 'l3': 150.03286388991287, 'l4': 170.00766335439425}
[0.21947762 0.64511496 0.63521101 0.56261529] {'l1': 111.2192385951849, 'l2': 199.9496250226288, 'l3': 149.96934278871845, 'l4': 169.95140182545327}
[ 0.21947762 -0.11013138 -0.10021375 -0.12889875] {'l1': 111.19729083343961, 'l2': 199.960638161001, 'l3': 149.9793641640786, 'l4': 169.96429170051405}
[ 0.21947762 -0.34219862 -0.32619034 -0.34138273] {'l1': 111.17534307169431, 'l2': 199.99485802255893, 'l3': 150.0119831980846, 'l4': 169.9984299737214}
[ 0.21947762 -0.41350674  0.65635858 -0.40667344] {'l1': 111.15339530994902, 'l2': 200.03620869658621, 'l3': 149.94634734011174, 'l4': 170.03909731788994}
[ 0.21947762  0.62382161 -0.09371567  0.48467183] {'l1': 111.13144754820372, 'l2': 199.97382653527436, 'l3': 149.9557189066262, 'l4': 169.99063013439186}
[ 0.21947762 -0.11667426 -0.32419365 -0.15284871] {'l1': 111.10949978645843, 'l2': 

[ 0.21947762 -0.11667426  0.65635311 -0.14721556] {'l1': 110.05600722268426, 'l2': 199.98142871830672, 'l3': 149.95241983454534, 'l4': 169.99212014341438}
[ 0.21947762 -0.34420907 -0.09371735 -0.347011  ] {'l1': 110.03405946093896, 'l2': 200.01584962528582, 'l3': 149.96179156907505, 'l4': 170.02682124382522}
[ 0.21947762  0.64511496 -0.32419417  0.50300452] {'l1': 110.01211169919367, 'l2': 199.9513381297771, 'l3': 149.99421098562982, 'l4': 169.97652079136273}
[ 0.21947762 -0.11013138 -0.3950136  -0.14721556] {'l1': 109.99016393744837, 'l2': 199.9623512681493, 'l3': 150.03371234551017, 'l4': 169.99124234761965}
[ 0.21947762 -0.34219862  0.63521101 -0.347011  ] {'l1': 109.96821617570308, 'l2': 199.99657112970723, 'l3': 149.97019124431574, 'l4': 170.0259434480305}
[ 0.21947762 -0.41350674 -0.10021375  0.50300452] {'l1': 109.94626841395778, 'l2': 200.03792180373452, 'l3': 149.98021261967588, 'l4': 169.975642995568}
[ 0.21947762  0.62382161 -0.32619034 -0.14721556] {'l1': 109.92432065221249

[ 0.21947762  0.62382161 -0.09371566 -0.14721556] {'l1': 108.87082808843832, 'l2': 199.9714743989625, 'l3': 149.94393088659572, 'l4': 169.97631981910914}
[ 0.21947762 -0.11667426 -0.32419365 -0.347011  ] {'l1': 108.84888032669302, 'l2': 199.98314182543564, 'l3': 149.9763502515105, 'l4': 170.01102091951998}
[ 0.21947762 -0.34420907 -0.39501344  0.50300452] {'l1': 108.82693256494773, 'l2': 200.0175627324282, 'l3': 150.01585159552323, 'l4': 169.96072046705748}
[ 0.21947762  0.64511496  0.63521106 -0.14721556] {'l1': 108.80498480320243, 'l2': 199.95305123692359, 'l3': 149.95233048945312, 'l4': 169.9754420233144}
[ 0.21947762 -0.11013138 -0.10021374 -0.347011  ] {'l1': 108.78303704145713, 'l2': 199.96406437529706, 'l3': 149.9623518633151, 'l4': 170.01014312372524}
[ 0.21947762 -0.34219862 -0.32619034  0.50300452] {'l1': 108.76108927971184, 'l2': 199.9982842368554, 'l3': 149.99497089686076, 'l4': 169.95984267126275}
[ 0.21947762 -0.41350674 -0.39562697 -0.14721556] {'l1': 108.73914151796654,

[ 0.21947762 -0.41350674 -0.10021374  0.48467228] {'l1': 107.68564895419237, 'l2': 200.03556966742266, 'l3': 149.96842460029066, 'l4': 169.9885482255092}
[ 0.21947762  0.62382161 -0.32619034 -0.15284858] {'l1': 107.66370119244708, 'l2': 199.9731875061108, 'l3': 150.00104363383633, 'l4': 170.0038330831052}
[ 0.21947762 -0.11667426  0.65635858  0.56266551] {'l1': 107.64175343070178, 'l2': 199.98485493258394, 'l3': 149.935407775722, 'l4': 169.94756653257434}
[ 0.21947762 -0.34420907 -0.09371566 -0.12888332] {'l1': 107.61980566895649, 'l2': 200.0192758395765, 'l3': 149.94477934219302, 'l4': 169.96045486463333}
[ 0.21947762  0.64511496 -0.32419365 -0.34137799] {'l1': 107.59785790721119, 'l2': 199.9547643440719, 'l3': 149.9771987071078, 'l4': 169.99459266371701}
[ 0.21947762 -0.11013138 -0.39501344 -0.40667198] {'l1': 107.5759101454659, 'l2': 199.96577748244536, 'l3': 150.01670005112052, 'l4': 170.0352598621999}
[ 0.21947762 -0.34219862  0.63521106  0.48467228] {'l1': 107.5539623837206, 'l2'

[ 0.21947762 -0.34219862 -0.32419365  0.50300452] {'l1': 106.50046981994643, 'l2': 199.99593210054368, 'l3': 149.98327144408336, 'l4': 169.97356106684535}
[ 0.21947762 -0.41350674 -0.39501344 -0.14721556] {'l1': 106.47852205820114, 'l2': 200.03728277457097, 'l3': 150.0227727880961, 'l4': 169.98828262310226}
[ 0.21947762  0.62382161  0.63521106 -0.347011  ] {'l1': 106.45657429645584, 'l2': 199.9749006132591, 'l3': 149.95925168202598, 'l4': 170.0229837235131}
[ 0.21947762 -0.11667426 -0.10021374  0.50300452] {'l1': 106.43462653471055, 'l2': 199.98656803973225, 'l3': 149.96927305588795, 'l4': 169.9726832710506}
[ 0.21947762 -0.34420907 -0.32619034 -0.14721556] {'l1': 106.41267877296525, 'l2': 200.0209889467248, 'l3': 150.00189208943362, 'l4': 169.98740482730753}
[ 0.21947762  0.64511496  0.65635858 -0.347011  ] {'l1': 106.39073101121996, 'l2': 199.9564774512202, 'l3': 149.9362562313193, 'l4': 170.02210592771837}
[ 0.21947762 -0.11013138 -0.09371566  0.50300452] {'l1': 106.36878324947466, 

[ 0.21947762 -0.11013138 -0.32619034  0.50300452] {'l1': 105.31529068570049, 'l2': 199.96342534613404, 'l3': 150.00796482640916, 'l4': 169.9577607425401}
[ 0.21947762 -0.34219862  0.65635858 -0.14721556] {'l1': 105.2933429239552, 'l2': 199.997645207692, 'l3': 149.94232896829487, 'l4': 169.97248229879702}
[ 0.21947762 -0.41350674 -0.09371566 -0.347011  ] {'l1': 105.2713951622099, 'l2': 200.03899588171927, 'l3': 149.95170053476588, 'l4': 170.00718339920786}
[ 0.21947762  0.62382161 -0.32419365  0.50300452] {'l1': 105.2494474004646, 'l2': 199.9766137204074, 'l3': 149.98411989968065, 'l4': 169.95688294674537}
[ 0.21947762 -0.11667426 -0.39501344 -0.14721556] {'l1': 105.22749963871931, 'l2': 199.98828114688055, 'l3': 150.02362124369338, 'l4': 169.97160450300228}
[ 0.21947762 -0.34420907  0.63521106 -0.347011  ] {'l1': 105.20555187697401, 'l2': 200.0227020538731, 'l3': 149.96010013762327, 'l4': 170.00630560341313}
[ 0.21947762  0.64511496 -0.10021374  0.50300452] {'l1': 105.18360411522872, '

[ 0.21947762  0.64511496 -0.3950136  -0.40667198] {'l1': 104.13011155145455, 'l2': 199.95412531490834, 'l3': 150.02969397363057, 'l4': 170.0331779334773}
[ 0.21947762 -0.11013138  0.63521101  0.48467228] {'l1': 104.10816378970925, 'l2': 199.9651384532818, 'l3': 149.96617287243615, 'l4': 169.98471070521384}
[ 0.21947762 -0.34219862 -0.10021375 -0.15284858] {'l1': 104.08621602796396, 'l2': 199.99935831484015, 'l3': 149.9761942477963, 'l4': 169.99999556279826}
[ 0.21947762 -0.41350674 -0.32619034 -0.34874188] {'l1': 104.06426826621866, 'l2': 200.04070898886755, 'l3': 150.0088132818023, 'l4': 170.03486975081387}
[0.21947762 0.62382161 0.65635858 0.50247267] {'l1': 104.04232050447337, 'l2': 199.97832682755572, 'l3': 149.94317742382944, 'l4': 169.984622483596}
[ 0.21947762 -0.11667426 -0.09371567 -0.14737899] {'l1': 104.02037274272807, 'l2': 199.98999425402886, 'l3': 149.9525489903439, 'l4': 169.99936038227244}
[ 0.21947762 -0.34420907 -0.32419365 -0.34706122] {'l1': 103.99842498098278, 'l2'

[ 0.21947762 -0.34420907  0.65635311 -0.347011  ] {'l1': 102.9449324172086, 'l2': 200.02034991756125, 'l3': 149.94924991826304, 'l4': 170.02002399899573}
[ 0.21947762  0.64511496 -0.09371735  0.50300452] {'l1': 102.92298465546331, 'l2': 199.95583842205664, 'l3': 149.95862165279274, 'l4': 169.96972354653323}
[ 0.21947762 -0.11013138 -0.32419417 -0.14721556] {'l1': 102.90103689371801, 'l2': 199.96685156043011, 'l3': 149.99104106934752, 'l4': 169.98444510279015}
[ 0.21947762 -0.34219862 -0.3950136  -0.347011  ] {'l1': 102.87908913197272, 'l2': 200.00107142198846, 'l3': 150.03054242922786, 'l4': 170.019146203201}
[0.21947762 0.64573271 0.63521101 0.50300452] {'l1': 102.85714137022742, 'l2': 199.9364981505374, 'l3': 149.96702132803344, 'l4': 169.9688457507385}
[ 0.21947762 -0.10994156 -0.10021375 -0.14721556] {'l1': 102.83519360848213, 'l2': 199.94749230679582, 'l3': 149.97704270339358, 'l4': 169.9835673069954}
[ 0.21947762 -0.34214029 -0.32619034 -0.347011  ] {'l1': 102.81324584673683, 'l2

[ 0.21947762 -0.11667426  0.63502254 -0.347011  ] {'l1': 101.75975328296266, 'l2': 199.987642117717, 'l3': 149.9730857049119, 'l4': 170.00422367469048}
[ 0.21947762 -0.34420907 -0.10027167  0.50300452] {'l1': 101.73780552121737, 'l2': 200.02206302470955, 'l3': 149.98311287153234, 'l4': 169.95392322222798}
[ 0.21947762  0.64511496 -0.32620814 -0.14721556] {'l1': 101.71585775947207, 'l2': 199.95755152920495, 'l3': 150.01573368503955, 'l4': 169.9686447784849}
[ 0.21947762 -0.11013138  0.65635311 -0.347011  ] {'l1': 101.69390999772678, 'l2': 199.96856466757842, 'l3': 149.95009837386033, 'l4': 170.00334587889574}
[ 0.21947762 -0.34219862 -0.09371735  0.50300452] {'l1': 101.67196223598148, 'l2': 200.00278452913676, 'l3': 149.95947010839004, 'l4': 169.95304542643325}
[ 0.21947762  0.64573271 -0.32419417 -0.14721556] {'l1': 101.65001447423619, 'l2': 199.9382112576857, 'l3': 149.9918895249448, 'l4': 169.96776698269016}
[ 0.21947762 -0.10994156 -0.3950136  -0.347011  ] {'l1': 101.62806671249089,

[ 0.21947762  0.62382161 -0.10021374 -0.1472203 ] {'l1': 100.57457414871672, 'l2': 199.97768779839217, 'l3': 149.96525468400836, 'l4': 169.99728549227012}
[ 0.21947762 -0.11667426 -0.32619034 -0.34701246] {'l1': 100.55262638697143, 'l2': 199.9893552248653, 'l3': 149.99787371755403, 'l4': 170.03198673836675}
[ 0.21947762 -0.34420907 -0.39562697  0.50300408] {'l1': 100.53067862522613, 'l2': 200.02377613185786, 'l3': 150.03743641445797, 'l4': 169.98168633066965}
[ 0.21947762  0.64511496  0.63502254 -0.1472157 ] {'l1': 100.50873086348084, 'l2': 199.95926463635325, 'l3': 149.9739341605092, 'l4': 169.9964079006818}
[ 0.21947762 -0.11013138 -0.10027167 -0.34701105] {'l1': 100.48678310173554, 'l2': 199.97027777472672, 'l3': 149.98396132712963, 'l4': 170.03110900531925}
[ 0.21947762 -0.34219862 -0.32620814  0.50300451] {'l1': 100.46483533999024, 'l2': 200.00449763628507, 'l3': 150.01658214063684, 'l4': 169.9808085541555}
[ 0.21947762  0.64573271  0.65635311 -0.14721557] {'l1': 100.4428875782449

[0.20971296 1.07063967 1.07934936 0.86766485] {'l1': 100.40636653358038, 'l2': 200.01841505597764, 'l3': 149.98665586353403, 'l4': 170.1039490731353}
[0.2164772  1.07986057 0.03625822 0.8762423 ] {'l1': 100.38471881404307, 'l2': 199.91042899938302, 'l3': 149.9830300416331, 'l4': 170.016324843308}
[ 0.21855567  0.02345445 -0.28425611  0.87887792] {'l1': 100.36286324733543, 'l2': 199.90808355456323, 'l3': 150.01145565274086, 'l4': 169.92843705103905}
[ 0.21919433 -0.30115122  0.66924386 -0.03171961] {'l1': 100.34094381468763, 'l2': 199.93819867669563, 'l3': 149.94453126678184, 'l4': 169.93160901155014}
[ 0.21939057 -0.40089396 -0.08975636 -0.31152215] {'l1': 100.319004757725, 'l2': 199.9782880728232, 'l3': 149.9535069027137, 'l4': 169.9627612265496}
[ 0.21945087 -0.43154227 -0.32297706 -0.39749807] {'l1': 100.29705967072927, 'l2': 200.02144229963832, 'l3': 149.98580460864187, 'l4': 170.00251103397963}
[ 0.2194694   0.61827977 -0.39463961  0.48749118] {'l1': 100.2751127308638, 'l2': 199.9

[ 0.21947755 -0.11018079 -0.39501027 -0.14735386] {'l1': 100.21859931346299, 'l2': 199.9500527222988, 'l3': 150.0318485544996, 'l4': 169.9789276358788}
[ 0.2194776  -0.3422138   0.63521204 -0.3470535 ] {'l1': 100.19665155391739, 'l2': 199.98427410184314, 'l3': 149.96832735089873, 'l4': 170.0136329858081}
[ 0.21947761 -0.4135114  -0.10021344  0.50299147] {'l1': 100.174703792848, 'l2': 200.0256252423075, 'l3': 149.9783486947921, 'l4': 169.96333383911028}
[ 0.21947762  0.62382018 -0.32619024 -0.14721957] {'l1': 100.15275603131039, 'l2': 199.96324322431943, 'l3': 150.0109677191292, 'l4': 169.97805579659416}
[ 0.21947762 -0.11667471  0.65635861 -0.34701224] {'l1': 100.1308082696289, 'l2': 199.97491069483218, 'l3': 149.94533185818534, 'l4': 170.01275702029145}
[ 0.21947762 -0.34420921 -0.09371566  0.50300415] {'l1': 100.1088605079032, 'l2': 200.00933161535693, 'l3': 149.9547034237869, 'l4': 169.96245660571162}
[ 0.21947762  0.64511491 -0.32419365 -0.14721568] {'l1': 100.08691274616393, 'l2':

[0.12363146 0.95346199 0.96174741 0.75439792] {'l1': 100.45990174961516, 'l2': 200.16189516551526, 'l3': 150.18079088225696, 'l4': 170.2497460767036}
[0.19002663 1.04385496 1.0521078  0.84143837] {'l1': 100.44089908677816, 'l2': 200.05750966916747, 'l3': 150.07558010230812, 'l4': 170.1656022400356}
[0.21042811 1.07163033 1.07987316 0.86818359] {'l1': 100.41985627606152, 'l2': 199.95034663583738, 'l3': 149.96759278660775, 'l4': 170.07878388056594}
[0.21669694 0.02092552 0.03641917 0.8764017 ] {'l1': 100.3981865818412, 'l2': 199.94825408430677, 'l3': 149.96395086989838, 'l4': 169.99114371095135}
[ 0.21862319 -0.3019283  -0.28420666 -0.03248048] {'l1': 100.37632426289447, 'l2': 199.97844691386067, 'l3': 149.99237153549706, 'l4': 169.9943917593572}
[ 0.21921507 -0.40113274 -0.38272649 -0.31175595] {'l1': 100.35440275546213, 'l2': 200.01856018742433, 'l3': 150.0306441849321, 'l4': 170.02556735415502}
[0.21939694 0.62762382 0.63898651 0.51383747] {'l1': 100.33246306097307, 'l2': 199.95579780

[ 0.21947688 -0.11663869 -0.39501344 -0.14711901] {'l1': 100.25150357183404, 'l2': 199.97379614241316, 'l3': 150.0234867225181, 'l4': 169.97374184273514}
[ 0.21947739 -0.34419814  0.63521106 -0.34698134] {'l1': 100.22955583265356, 'l2': 200.0082159564151, 'l3': 149.959965616448, 'l4': 170.0084399762369}
[ 0.21947755  0.64511831 -0.10021374  0.50301364] {'l1': 100.20760807784183, 'l2': 199.9437041250634, 'l3': 149.96998699030996, 'l4': 169.95813861212167}
[ 0.2194776  -0.11013035 -0.32619034 -0.14721276] {'l1': 100.18566031822702, 'l2': 199.9547171602399, 'l3': 150.00260602385563, 'l4': 169.97285988825183}
[ 0.21947761 -0.3421983   0.65635858 -0.34701014] {'l1': 100.16371255713636, 'l2': 199.98893699008855, 'l3': 149.93697016574131, 'l4': 170.00756090258713}
[ 0.21947762 -0.41350664 -0.09371566  0.50300479] {'l1': 100.14176479559222, 'l2': 200.0302876543724, 'l3': 149.94634173221232, 'l4': 169.9572604236759}
[ 0.21947762  0.62382164 -0.32419365 -0.14721548] {'l1': 100.11981703390873, 'l

[0.12363146 0.95346199 0.955251   0.74860162] {'l1': 100.5100687440576, 'l2': 200.16774033091852, 'l3': 150.18940373555134, 'l4': 170.26155546561307}
[0.19002663 1.04385496 1.05011162 0.83965732] {'l1': 100.49106608122077, 'l2': 200.06335483456314, 'l3': 150.0843925731701, 'l4': 170.17758973389493}
[0.21042811 1.07163033 1.07925978 0.86763633] {'l1': 100.47002327050417, 'l2': 199.95619180123074, 'l3': 149.97646659467054, 'l4': 170.09082610136738}
[0.21669694 0.02092552 0.03623069 0.87623353] {'l1': 100.44835357628386, 'l2': 199.95409924969942, 'l3': 149.97284352526128, 'l4': 170.0032027478952}
[ 0.21862319 -0.3019283  -0.28426457  0.87887523] {'l1': 100.42649125733713, 'l2': 199.9842920792531, 'l3': 150.00126998213696, 'l4': 169.91531522490698}
[ 0.21921507 -0.40113274  0.66924126 -0.03172043] {'l1': 100.4045697499048, 'l2': 200.0244053528167, 'l3': 149.93434585606005, 'l4': 169.91848726816093}
[ 0.21939694  0.62762382 -0.08975716 -0.3115224 ] {'l1': 100.38263005541573, 'l2': 199.96164

In [10]:
end = time.time()
print(end-start)

920.4312827587128
